In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

mnist = tf.keras.datasets.mnist
tf.reset_default_graph()
(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
print(x_train.shape)
x_train=x_train.reshape(x_train.shape[0],28*28)
x_test=x_test.reshape(x_test.shape[0],28*28)
y_train=pd.get_dummies(y_train)
y_test=pd.get_dummies(y_test)

print(y_train.shape)
## Define a Logistic Regression in TF
### y = sigmoid(Wx+b)
## Dim(b) = 10
## Dim(x) = 784
## Dim(Wx) = 10



D:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


(60000, 28, 28)
(60000, 10)


In [ ]:
x=tf.placeholder(tf.float32,(None,784))
y=tf.placeholder(tf.float32,(None,10))
pred_x=tf.placeholder(tf.float32,(None,784))

W=tf.Variable(tf.random_normal((784,10)))
b=tf.Variable(tf.random_normal((10,)))

y_logit = tf.squeeze(tf.matmul(x, W) + b)

entropy = tf.nn.sigmoid_cross_entropy_with_logits(logits=y_logit, labels=y)
l = tf.reduce_sum(entropy)

train_op = tf.train.AdamOptimizer(.01).minimize(l)

n_steps = 100

pred_y = tf.nn.softmax(tf.matmul(pred_x,W) + b)
pred=tf.argmax(pred_y, 1)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) # Train model
    for i in range(n_steps):
        feed_dict = {x: x_train, y: y_train}
        _, loss = sess.run([train_op, l], feed_dict=feed_dict) 
        print("Current Loss: %f" %loss)
    writer = tf.summary.FileWriter('./graph',sess.graph)
    preds=sess.run(pred,feed_dict={pred_x:x_test})
print(preds

In [12]:
x_train.shape

(60000, 784)

In [2]:
y_test


0  1  2  3  4  5  6  7  8  9
0     0  0  0  0  0  0  0  1  0  0
1     0  0  1  0  0  0  0  0  0  0
2     0  1  0  0  0  0  0  0  0  0
3     1  0  0  0  0  0  0  0  0  0
4     0  0  0  0  1  0  0  0  0  0
5     0  1  0  0  0  0  0  0  0  0
6     0  0  0  0  1  0  0  0  0  0
7     0  0  0  0  0  0  0  0  0  1
8     0  0  0  0  0  1  0  0  0  0
9     0  0  0  0  0  0  0  0  0  1
10    1  0  0  0  0  0  0  0  0  0
11    0  0  0  0  0  0  1  0  0  0
12    0  0  0  0  0  0  0  0  0  1
13    1  0  0  0  0  0  0  0  0  0
14    0  1  0  0  0  0  0  0  0  0
15    0  0  0  0  0  1  0  0  0  0
16    0  0  0  0  0  0  0  0  0  1
17    0  0  0  0  0  0  0  1  0  0
18    0  0  0  1  0  0  0  0  0  0
19    0  0  0  0  1  0  0  0  0  0
20    0  0  0  0  0  0  0  0  0  1
21    0  0  0  0  0  0  1  0  0  0
22    0  0  0  0  0  0  1  0  0  0
23    0  0  0  0  0  1  0  0  0  0
24    0  0  0  0  1  0  0  0  0  0
25    1  0  0  0  0  0  0  0  0  0
26    0  0  0  0  0  0  0  1  0  0
27    0  0  0  0  1  0  0  0  0  0
28    1  0  0  0  0  0  0  0  0  0
29    0  1  0  0  0  0  0  0  0  0
...  .. .. .. .. .. .. .. .. .. ..
9970  0  0  0  0  0  1  0  0  0  0
9971  0  0  1  0  0  0  0  0  0  0
9972  0  0  0  0  1  0  0  0  0  0
9973  0  0  0  0  0  0  0  0  0  1
9974  0  0  0  0  1  0  0  0  0  0
9975  0  0  0  1  0  0  0  0  0  0
9976  0  0  0  0  0  0  1  0  0  0
9977  0  0  0  0  1  0  0  0  0  0
9978  0  1  0  0  0  0  0  0  0  0
9979  0  0  0  0  0  0  0  1  0  0
9980  0  0  1  0  0  0  0  0  0  0
9981  0  0  0  0  0  0  1  0  0  0
9982  0  0  0  0  0  1  0  0  0  0
9983  1  0  0  0  0  0  0  0  0  0
9984  0  1  0  0  0  0  0  0  0  0
9985  0  0  1  0  0  0  0  0  0  0
9986  0  0  0  1  0  0  0  0  0  0
9987  0  0  0  0  1  0  0  0  0  0
9988  0  0  0  0  0  1  0  0  0  0
9989  0  0  0  0  0  0  1  0  0  0
9990  0  0  0  0  0  0  0  1  0  0
9991  0  0  0  0  0  0  0  0  1  0
9992  0  0  0  0  0  0  0  0  0  1
9993  1  0  0  0  0  0  0  0  0  0
9994  0  1  0  0  0  0  0  0  0  0
9995  0  0  1  0  0  0  0  0  0  0
9996  0  0  0  1  0  0  0  0  0  0
9997  0  0  0  0  1  0  0  0  0  0
9998  0  0  0  0  0  1  0  0  0  0
9999  0  0  0  0  0  0  1  0  0  0

[10000 rows x 10 columns]

In [17]:
from sklearn.linear_model import LogisticRegression
def get_digit(row):
    for c in y_train.columns:
        if row[c]==1:
            return c
y_train_sklog = y_train.apply(get_digit,axis=1)
clf = LogisticRegression(random_state = 0, solver = 'lbfgs' , multi_class='multinomial').fit(x_train,y_train_sklog)
clf.predict(x_test)

D:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:757: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [19]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf
import numpy as np
import pandas as pd

mnist = tf.keras.datasets.mnist
tf.reset_default_graph()
(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train=x_train.reshape(x_train.shape[0],28*28)
x_test=x_test.reshape(x_test.shape[0],28*28)
y_train=pd.get_dummies(y_train)
y_test=pd.get_dummies(y_test)

### Y=Act(W*Act(W*Act(...+b)+b)+b)
### Dim(y)*10
### Dim(Act(W*Act(...)+b)+b)*10

### Dim(Act(W*x_input+b))=N
### Dim(b) = N
### Dim(x_input) = 784
### Dim(W)

x=tf.placeholder(tf.float32,(None,784))
y=tf.placeholder(tf.float32,(None,10))
x_pred=tf.placeholder(tf.float32,(None,784))

w1=tf.Variable(tf.random_normal((784,1024)))
b1=tf.Variable(tf.random_normal((1024,)))

w2=tf.Variable(tf.random_normal((1024,512)))
b2=tf.Variable(tf.random_normal((512,)))

w3=tf.Variable(tf.random_normal((512,64)))
b3=tf.Variable(tf.random_normal((64,)))

w4=tf.Variable(tf.random_normal((64,10)))
b4=tf.Variable(tf.random_normal((10,)))

layer1=tf.matmul(x,w1)+b1
layer1_activation=tf.nn.relu(layer1)

layer2=tf.matmul(layer1_activation,w2)+b2
layer2_activation=tf.nn.relu(layer2)

layer3=tf.matmul(layer2_activation,w3)+b3
layer3_activation=tf.nn.relu(layer3)

layer4=tf.matmul(layer3_activation,w4)+b4
layer4_activation=tf.nn.softmax(layer4)

entropy = tf.nn.sigmoid_cross_entropy_with_logits(logits=layer4, labels=y)
l = tf.reduce_sum(entropy)
train_op = tf.train.AdamOptimizer(.01).minimize(l)
n_steps = 13
#pred_y = tf.nn.softmax(tf.matmul(pred_x,W) + b)
pred=tf.argmax(layer4_activation, 1)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) # Train model
    for i in range(n_steps):
        feed_dict = {x: x_train, y: y_train}
        _, loss = sess.run([train_op, l], feed_dict=feed_dict)
        print("Current Loss: %f" %loss)
    writer = tf.summary.FileWriter('./graph', sess.graph)
    preds=sess.run(pred,feed_dict={x:x_test})
print(preds)


Current Loss: 5847003136.000000
Current Loss: 2402704896.000000
Current Loss: 1271025280.000000
Current Loss: 1094157184.000000
Current Loss: 1114293632.000000
Current Loss: 1054869824.000000
Current Loss: 923103744.000000
Current Loss: 754641792.000000
Current Loss: 598498944.000000
Current Loss: 476894016.000000
Current Loss: 386014432.000000
Current Loss: 319635616.000000
Current Loss: 263243264.000000
[7 2 1 ... 4 5 5]


In [2]:
from keras.models import Sequential
from keras.layers import Activation
from keras.optimizers import Adam
from keras.layers import Dense

model = Sequential()
model.add(Dense(1024, input_dim=784,init='normal',activation='relu'))
model.add(Dense(512, activation = 'relu',kernel_initializer = 'normal'))
model.add(Dense(64,activation = 'relu', kernel_initializer = 'uniform'))
model.add(Dense(10))
model.add(Activation('softmax'))
optimizer = Adam(lr=0.01)
model.compile(loss='binary_crossentropy',optimizer = optimizer, metrics = ['accuracy'])
model.fit(x_train,y_train,epochs = 13, batch_size=128,verbose=1)

Using TensorFlow backend.
D:\anaconda\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1024, input_dim=784, activation="relu", kernel_initializer="normal")`
  import sys


Epoch 1/13
60000/60000 [==============================] - 22s 366us/step - loss: 0.0583 - acc: 0.9818
Epoch 2/13
60000/60000 [==============================] - 23s 389us/step - loss: 0.0256 - acc: 0.9919
Epoch 3/13
60000/60000 [==============================] - 22s 362us/step - loss: 0.0200 - acc: 0.9937
Epoch 4/13
60000/60000 [==============================] - 21s 353us/step - loss: 0.0184 - acc: 0.9943
Epoch 5/13
60000/60000 [==============================] - 22s 359us/step - loss: 0.0164 - acc: 0.9950
Epoch 6/13
60000/60000 [==============================] - 22s 370us/step - loss: 0.0158 - acc: 0.99531s - loss:
Epoch 7/13
60000/60000 [==============================] - 22s 361us/step - loss: 0.0139 - acc: 0.9959
Epoch 8/13
60000/60000 [==============================] - 24s 399us/step - loss: 0.0132 - acc: 0.9961
Epoch 9/13
60000/60000 [==============================] - 22s 367us/step - loss: 0.0118 - acc: 0.9965
Epoch 10/13
60000/60000 [==============================] - 21s 357us/ste

In [14]:
pd.DataFrame(model.predict(x_test)).round().astype(int)

0  1  2  3  4  5  6  7  8  9
0     0  0  0  0  0  0  0  1  0  0
1     0  0  1  0  0  0  0  0  0  0
2     0  1  0  0  0  0  0  0  0  0
3     1  0  0  0  0  0  0  0  0  0
4     0  0  0  0  1  0  0  0  0  0
5     0  1  0  0  0  0  0  0  0  0
6     0  0  0  0  1  0  0  0  0  0
7     0  0  0  0  0  0  0  0  0  1
8     0  0  0  0  0  1  0  0  0  0
9     0  0  0  0  0  0  0  0  0  1
10    1  0  0  0  0  0  0  0  0  0
11    0  0  0  0  0  0  1  0  0  0
12    0  0  0  0  0  0  0  0  0  1
13    1  0  0  0  0  0  0  0  0  0
14    0  1  0  0  0  0  0  0  0  0
15    0  0  0  0  0  1  0  0  0  0
16    0  0  0  0  0  0  0  0  0  1
17    0  0  0  0  0  0  0  1  0  0
18    0  0  0  1  0  0  0  0  0  0
19    0  0  0  0  1  0  0  0  0  0
20    0  0  0  0  0  0  0  0  0  1
21    0  0  0  0  0  0  1  0  0  0
22    0  0  0  0  0  0  1  0  0  0
23    0  0  0  0  0  1  0  0  0  0
24    0  0  0  0  1  0  0  0  0  0
25    1  0  0  0  0  0  0  0  0  0
26    0  0  0  0  0  0  0  1  0  0
27    0  0  0  0  1  0  0  0  0  0
28    1  0  0  0  0  0  0  0  0  0
29    0  1  0  0  0  0  0  0  0  0
...  .. .. .. .. .. .. .. .. .. ..
9970  0  0  0  0  0  1  0  0  0  0
9971  0  0  1  0  0  0  0  0  0  0
9972  0  0  0  0  1  0  0  0  0  0
9973  0  0  0  0  0  0  0  0  0  1
9974  0  0  0  0  1  0  0  0  0  0
9975  0  0  0  1  0  0  0  0  0  0
9976  0  0  0  0  0  0  1  0  0  0
9977  0  0  0  0  1  0  0  0  0  0
9978  0  1  0  0  0  0  0  0  0  0
9979  0  0  0  0  0  0  0  1  0  0
9980  0  0  0  1  0  0  0  0  0  0
9981  0  0  0  0  0  0  1  0  0  0
9982  0  0  0  0  0  0  1  0  0  0
9983  1  0  0  0  0  0  0  0  0  0
9984  0  1  0  0  0  0  0  0  0  0
9985  0  0  1  0  0  0  0  0  0  0
9986  0  0  0  1  0  0  0  0  0  0
9987  0  0  0  0  1  0  0  0  0  0
9988  0  0  0  0  0  1  0  0  0  0
9989  0  0  0  0  0  0  1  0  0  0
9990  0  0  0  0  0  0  0  1  0  0
9991  0  0  0  0  0  0  0  0  1  0
9992  0  0  0  0  0  0  0  0  0  1
9993  1  0  0  0  0  0  0  0  0  0
9994  0  1  0  0  0  0  0  0  0  0
9995  0  0  1  0  0  0  0  0  0  0
9996  0  0  0  1  0  0  0  0  0  0
9997  0  0  0  0  1  0  0  0  0  0
9998  0  0  0  0  0  1  0  0  0  0
9999  0  0  0  0  0  0  1  0  0  0

[10000 rows x 10 columns]

In [18]:
import time
import sklearn.preprocessing
import os
import math


import tensorflow as tf
import numpy as np
import pandas as pd

mnist = tf.keras.datasets.mnist
(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

label_binarizer = sklearn.preprocessing.LabelBinarizer()
y_train = label_binarizer.fit_transform(y_train)
print(x_train.shape)
batch_size=128
learning_rate=0.002

#sess=tf.Session()
X=tf.placeholder(tf.float32,[None,28,28])
Y=tf.placeholder(tf.float32,[None,10])
X_img=tf.reshape(X,[-1,28,28,1])

## Convolutional w. dropout Layer 1
W1=tf.Variable(tf.random_normal([3,3,1,32],stddev=0.01))
L1=tf.nn.conv2d(X_img,W1,strides=[1,1,1,1],padding="SAME")
L1=tf.nn.relu(L1)
L1=tf.nn.max_pool(L1,ksize=[1,2,2,1],strides=[1,2,2,1],padding="SAME")
## 14*14*32


## Convolutional w. dropout Layer 2
W2=tf.Variable(tf.random_normal([3,3,32,64],stddev=0.01))
L2=tf.nn.conv2d(L1,W2,strides=[1,1,1,1],padding="SAME")
L2=tf.nn.relu(L2)
L2=tf.nn.max_pool(L2,ksize=[1,2,2,1],strides=[1,2,2,1],padding="SAME")
## 7*7*64

## Convolutional w. dropout Layer 3
W3=tf.Variable(tf.random_normal([3,3,64,128],stddev=0.01))
L3=tf.nn.conv2d(L2,W3,strides=[1,1,1,1],padding="SAME")
L3=tf.nn.relu(L3)
## 7*7*128

## Dense Layer 
L3=tf.reshape(L3,[-1,7*7*128])
W4=tf.Variable(tf.random_normal([7*7*128,10],stddev=0.01))
B4=tf.Variable(tf.random_normal([10]))

### Preidctin the result before SoftMax
predicted=tf.nn.softmax(tf.matmul(L3,W4)+B4)

## Weight initializer
##initializer=tf.contrib.layers.xavier_initializer()
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=predicted, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

def getBatch(i, size):
    startIndex = (i * size) % 59000
    endIndex = startIndex + size
    batch_X = x_train[startIndex : endIndex]
    batch_Y = y_train[startIndex : endIndex]
    return batch_X, batch_Y

def training_step(i):

    size = 128
    batch_X, batch_Y = getBatch(i, size)

    _,l=sess.run([optimizer,cost], feed_dict={X: batch_X, Y: batch_Y})
    print("Loss: %f" %l)

# Run number of iterations training the NN    
for i in range(50): 
    training_step(i)

writer = tf.summary.FileWriter('./graph', sess.graph)
pred=tf.argmax(predicted, 1)
preds=sess.run(pred,feed_dict={X:x_test})



(60000, 28, 28)
Loss: 2.300814
Loss: 2.312197
Loss: 2.311576
Loss: 2.298540
Loss: 2.297758
Loss: 2.289298
Loss: 2.278234
Loss: 2.250938
Loss: 2.184938
Loss: 2.136972
Loss: 2.139552
Loss: 2.105212
Loss: 2.021160
Loss: 1.891715
Loss: 1.912781
Loss: 1.872192
Loss: 1.858189
Loss: 1.854814
Loss: 1.875442
Loss: 1.799815
Loss: 1.890059
Loss: 1.886279
Loss: 1.762973
Loss: 1.927277
Loss: 1.884051
Loss: 1.959914
Loss: 1.818834
Loss: 1.862685
Loss: 1.829859
Loss: 1.811742
Loss: 1.793998
Loss: 1.910514
Loss: 1.840389
Loss: 1.855456
Loss: 1.820123
Loss: 1.743930
Loss: 1.876814
Loss: 1.820934
Loss: 1.805768
Loss: 1.788914
Loss: 1.817263
Loss: 1.797530
Loss: 1.815761
Loss: 1.843626
Loss: 1.832769
Loss: 1.819125
Loss: 1.781228
Loss: 1.749899
Loss: 1.856167
Loss: 1.845876


In [26]:
preds



array([7, 2, 1, ..., 4, 8, 6])

In [27]:
y_test



array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)